### ISSUE TITLE
raise AttributeError(str(ex)) AttributeError: 'DESCRIPTOR'  while converting json string to types.AnnotateFileResponse

### ISSUE THREAD

**Issue by saitej09** [googleapis/python-vision#106] opened 2021-02-11 13:43 UTC
#### Environment details

  - OS type and version: linux
  - Python version:   3.7.9
  - pip version: 20.3.3
  - `google-cloud-vision` version: `pip show google-cloud-vision`    2.0.0

#### Code example

```python
# example
from google.protobuf import json_format

json_string = blob.download_as_string()
response = json_format.Parse(json_string, types.AnnotateFileResponse())

```

#### Stack trace

parser.ConvertMessage(js_dict, message)
message_descriptor = message.DESCRIPTOR

raise AttributeError(str(ex))
AttributeError: 'DESCRIPTOR'
```

When I try to convert the json_string to AnnotateFileResponse, I am getting the above error.  I suppose it might be due to the usage of proto-plus as mentioned [here] (https://github.com/googleapis/python-memcache/issues/19#issuecomment-708516816) Can anyone give a possible fix.

**Comment by morgandu** [comment] 2021-02-13 01:53
Can you provide more context of your code, for example what is the content and format of your blob? 

Also, what you are trying to do with types.AnnotateFileResponse() with the json_string?

**Comment by saitej09** [comment] 2021-02-15 05:44
@morgandu 

I have called the **async_batch_annotate_files**  API and I am trying to perform simple post analysis by fetching the annotation text from the output stored on the GCS. So basically, i want to fetch text annotation from the blob.

The blob I am trying to analyse is an output from **async_batch_annotate_files**.  I am downloading the blob as json_string & converting to an annotation response. 


    ```
    json_string = blob.download_as_string()
    response = json_format.Parse(json_string, vision.types.AnnotateFileResponse())
```
I am getting the error when I am trying to execute the json_format. This works for the older versions of the vision API.

**Comment by morgandu** [comment] 2021-03-03 22:22
Thanks for clarifying. You are right, the issue was caused by the usage of proto-plus, and lead to the error [in](https://github.com/protocolbuffers/protobuf/blob/4baed791f514fec3a82417ae50acfabf841004eb/python/google/protobuf/json_format.py#L468).

Assigning to @busunkim96 since she has a lot of knowledge around issues like this.

**Comment by busunkim96** [comment] 2021-03-03 22:42
Hi,

Because proto-plus is a wrapper around protobuf the plain protobuf methods do not work for loading to/from JSON. You should use the proto-plus equivalents for loading to/from dicts and JSON strings.

https://proto-plus-python.readthedocs.io/en/latest/reference/message.html#proto.message.Message.from_json
https://proto-plus-python.readthedocs.io/en/latest/messages.html#serialization

Something like this should work:
```python
from google.cloud import vision

json_string = blob.download_as_string()
response = vision.AnnotateFileResponse.from_json(json_string)
```

**Comment by parthea** [comment] 2021-08-10 16:46
Hi @saitej09, I'm going to close this issue as a response was provided in https://github.com/googleapis/python-vision/issues/106#issuecomment-790125057 but please feel free to re-open this issue if you have additional questions.

**Closed by parthea** 2021-08-10 16:46 UTC
Labels: api: vision, status: investigating
